#!/bin/bash

# parameters:
# $1 = directory from which to get problems
# $2 = directory in which to store results
# $3 = time limit in seconds
# $4 = script to run for each problem
# $5 = team to run

if [[ $# -ne 5 ]]; then
  echo "usage: run_all <problem-directory> <results-directory> <time-limit> <run-one-script> <team-number>"
  exit 1;
fi

for j in $(find $1 -name "*.json"); do
  for i in lightning_builds/$5; do
    TEAM=$(basename $i)
    TEAMDIR=`pwd`/$i
    echo "Team $TEAM";
    SCORES=$(cd $(dirname "$2") && pwd -P)/$(basename "$2")/$TEAM
    PROBLEM=$(basename $j);	
    PROBLEMFILE=$(cd $(dirname "$j") && pwd -P)/$PROBLEM
    echo "Problem $PROBLEM enqueued"
    tsp -n -L $TEAM-$PROBLEM $4 $TEAMDIR $SCORES $PROBLEMFILE $3
  done
done

echo "all problems enqueued, check tsp for details"

