#!/bin/bash
TEAMDIR=$1
SCORESDIR=$2
PROBLEM=$3
TIMELIMIT=$4

mkdir -p $SCORESDIR
cd $TEAMDIR
PROBLEMNAME=$(basename $PROBLEM)
timeout $(($TIMELIMIT + 20)) ./play_icfp2015 -f $PROBLEM -t $TIMELIMIT -m 1024 \
      -p "pkkpdbbd" \
      -p "aaaabbbb" \
      -p "aabllp" \
      -p "ssseespsps" \
      -p "uuuuu" \
      -p "ddddd" \
      > $SCORESDIR/$PROBLEMNAME 2> $SCORESDIR/$PROBLEMNAME.err 

